### ISSUE TITLE
Allow for fake result columns

### ISSUE THREAD

**Issue by galeaspablo** [fourlabsldn/QBJSParserBundle#8]
From current documentation,
```
fl_qbjs_parser:
    builders: 
        product_report_builder:
            class: AppBundle\Entity\Product # this class must exist in doctrine_class_and_mappings
            human_readable_name: 'Product Report Builder'
            # result_columns
            # Not being used inside the bundle, but you can use them in your own way 
            # Make sure not to use OnetoMany or ManyToMany properties here. That makes no sense!
            # I.e. You can use direct properties of the class, ManyToOne, and OneToOne properties.
            result_columns: 
                -
                    column_machine_name: id
                    column_human_readable_name: ID
                -
                    column_machine_name: period.startDate
                    column_human_readable_name: Interview Start
                -
                    column_machine_name: period.endDate
                    column_human_readable_name: Interview End
```

Result columns shouldn't be limited. These are only used to build a query if they're used as sortable columns. Hence it's a good idea to put a `column_is_fake` option. Which should be false by default.
